name: stereoadapter2
channels:
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - pytorch-cuda
  - matplotlib
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - opt_einsum
  - imageio
  - scikit-image
  - ninja
  - pip:
    - einops
    - timm
    - mamba-ssm
    - triton
    - packaging
    - safetensors
    - huggingface-hub
